seed: 1337
device: "auto"        # "cuda", "cpu", or "auto"
data_root: "data/physionet_gait"
input_len: 2048       # samples per segment
n_channels: 8
batch_size: 64
epochs: 5
lr: 0.001
out_dir: "runs/diag_default"
model:
  n_filters: 16
  kernel_size: 129
  sample_rate: 100.0
