seed: 1337
device: "auto"
data_root: "data/physionet_gait"
input_len: 2048
n_channels: 8
batch_size: 64
epochs: 10
lr: 0.0007
out_dir: "runs/severity_default"
model:
  n_filters: 24
  kernel_size: 129
  sample_rate: 100.0
task: "regression"   # replaces default classification head
